[project]
name = "bluesnoop"
version = "0.1.0"
description = "A TUI bluetooth utility for radar analysis and war driving ðŸ¦‰"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleak>=2.1.1",
    "rich>=14.3.2",
]
